spring:
  application:
    name: bank-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:test_bank_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Arthur010279+}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: BankHikariPool
      minimum-idle: 5
      maximum-pool-size: 20
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        default_schema: transfer
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: transfer
    parameters:
      appSchema: transfer
    test-rollback-on-update: true

server:
  port: 8093
  servlet:
    context-path: /api/transfer
  shutdown: graceful
  error:
    include-message: always
    include-binding-errors: always